objects : headers.h main.c creation_database.c slowest_time.c distance_from_origin.c time_between_origin_station.c time_between_stations.c next_station_name.c prev_station_name.c fastest_time.c remaining_time.c distance_stations.c

output : $(objects)
	gcc -o output $(objects)

.PHONY : clean

clean :
	rm output
